Add dashboard and main pages
AntonKosmovskyXB/vehicle-tracking-demo pull request #2
Opened 2021-11-17 09:51 UTC by AntonKosmovskyXB

2021-11-17 10:59 UTC, AntonKosmovskyXB commented on sources/views/map.js
> +								}
Здесь конечно плохо, но пока не придумал как сделать лучше

2021-11-17 13:11 UTC, AntonKosmovskyXB commented on sources/views/map.js
> +										if (this.data.status === "Без маршрута") {
Можно ли так сделать? Мне, с одной стороны, желательно чтобы this указывало на темплейт, но при этом указатель на класс тоже нужен

2021-11-17 13:11 UTC, AntonKosmovskyXB commented on sources/views/map.js
> +										const currentClass = this.$scope;
Можно ли так сделать? Мне, с одной стороны, желательно чтобы this указывало на темплейт, но при этом указатель на класс тоже нужен

2021-11-17 14:25 UTC, AlexeyXB requested changes

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/dashboard.js
> +											if (value === "Изменился угол наклона") {
1. Много однотипного кода, в функцию define можно передать объект, и в таком случае его можно создать заранее и в каждом отдельном if менять только специфичные параметры.
2. Тут код больше подходит для реализации switch case default
3. value === "что-то" - так себе вариант, лучше бы сделать для этих строк какую-нибудь константу.

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/cars.js
> +			height: 5000,
Пугающе большая высота) может есть другой путь ? :)

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/dashboard.js
> +								values: [{text: "Изменился угол наклона", color: "#024ED7"}, {text: "Сошел с маршрута", color: "#F90C0C"}, {text: "Превысил скорость", color: "#04CC67"}],
Тут, как и в onChange мы используем те же строки, значит они очень просятся в константы

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/dashboard.js
> +								template: function (value) {
Лучше бы стрелочная функция. Будет аккуратнее и короче

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/dashboard.js
> +									return (value % 20 ? "" : value);
Тут тоже лучше стрелочная

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/dashboard.js
> +												this.$$("mileAgeChart").define("value", "#mileAge19#");
Вот такая конструкция встречается неоднократно, так что можно вынести ее в отдельную функцию, куда в качестве параметра передавать нужную строку.

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/map.js
> +								}
Да, нужно что-то другое придумать, что-то попроще... 
Как минимум можно обернуть `formValues` в `Object.keys()` и простись find-м.. По поводу `$$(card${i}).show();` - вроде в последних редакциях JS можно писать `$$(card${i})?.show()`. тем самым избавляясь от 
```
if ($$(`card${i}`)) {
    $$(`card${i}`).show();
}
```

2021-11-17 14:25 UTC, AlexeyXB commented on sources/views/map.js
> +										const currentClass = this.$scope;
Лучше перед `const newDriver = {` сделать переменную `const that = this;`

2021-11-18 08:40 UTC, AlexeyXB requested changes

2021-11-18 08:40 UTC, AlexeyXB commented on sources/views/map.js
> +											this.destructor();
Возможно лучше сделать через removeView()  у родителя

2021-11-18 08:40 UTC, AlexeyXB commented on sources/views/map.js
> +											const mymap = mapObj.setView(this.data.startCoord, 7);
Что означает цифра 7?

2021-11-18 08:40 UTC, AlexeyXB commented on sources/views/map.js
> +											this.destructor();
Тут тоже destructor, который правильнее было бы заменить на removeView()

2021-11-18 08:47 UTC, AntonKosmovskyXB commented on sources/views/map.js
> +											this.destructor();
Если речь про ближайшего родителя, то у scrollview нет такого метода

2021-11-18 08:47 UTC, AntonKosmovskyXB commented on sources/views/map.js
> +											const mymap = mapObj.setView(this.data.startCoord, 7);
Приближение на карте

2021-11-18 09:06 UTC, AlexeyXB approved these changes

2021-11-18 09:35 UTC, merged