Full version
AntonKosmovskyXB/vehicle-tracking-demo pull request #4
Opened 2021-12-02 11:21 UTC by AntonKosmovskyXB

2021-12-02 12:12 UTC, AlexeyXB requested changes

2021-12-02 12:12 UTC, AlexeyXB commented on sources/helpers/cardsFilter.js
> +	for (let i = 0; i < cards.length; i++) {
Кстати, а откуда здесь cards? Я не вижу где мы их объявляем а на входе тоже нету.

2021-12-02 12:12 UTC, AlexeyXB commented on sources/views/cars.js
> +											this.$$("carPhoto").setValues({Photo: reader.result});
Лучше бы вынести carPhoto и photoUploader в свойства класса, чтобы проще было к ним обращаться и меньше вызывать функцию поиска элемента по id.

2021-12-02 12:12 UTC, AlexeyXB commented on sources/views/cars.js
> +			this.$$("headLabel").define("label", editCarText);
Тут сразу два момента.
1) this.$$("photoUploader") и this.$$("headLabel") лучше вынести в переменные класса this.photoUploader и this.headLabel.
2) Ты в каждом случае вызываешь this.$$("photoUploader").refresh(); this.$$("headLabel").refresh(); поэтому их можно вынести за пределы if else

2021-12-02 12:12 UTC, AlexeyXB commented on sources/views/drivers.js
> +			this.$$("headLabel").define("label", editDriverText);
Тут похожая ситуация, как в предыдущем файле. Вынести refresh за пределы if else и сделать переменную this.headLabel. А если заморочиться, то можно сделать через сеттер.

2021-12-02 12:12 UTC, AlexeyXB commented on sources/views/trackers.js
> +			this.$$("headLabel").define("label", editTrackerText);
Здесь тоже лучше повыносить $$('')

2021-12-02 13:50 UTC, AntonKosmovskyXB commented on sources/helpers/cardsFilter.js
> +	for (let i = 0; i < cards.length; i++) {
Не совсем понял идею с двумя массивами. Подготовленные id всмысле id вьюшек?

2021-12-02 13:54 UTC, AlexeyXB commented on sources/helpers/cardsFilter.js
> +	for (let i = 0; i < cards.length; i++) {
Да, создаешь объект
```
cardIds: {
    show: [],
    hide: []
}
```
Потом делаешь всю магию по hide и show элементов

2021-12-03 06:35 UTC, AlexeyXB approved these changes

2021-12-07 07:51 UTC, merged